repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^api/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        files: ^api/
        language: system           
        args:
          - --explicit-package-bases
          - --namespace-packages

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        files: ^api/
        args: ["--fix"]
