FROM python:3.10-bullseye

RUN python -m pip install --upgrade pip
RUN pip install poetry

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

WORKDIR /app

# Disable Poetry virtualenv creation to install packages globally in container
ENV POETRY_VIRTUALENVS_CREATE=false

COPY pyproject.toml poetry.lock* /app/
RUN poetry install --no-interaction --no-ansi --no-root

COPY . /app

ENV PYTHONPATH=/app

CMD /wait && poetry run python -m api.migrations up && poetry run uvicorn api.main:app --reload --host 0.0.0.0
